# Generated by Django 3.2 on 2021-04-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan_apparel', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
    ]
