# Generated by Django 3.2 on 2021-04-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_apparel', '0005_product_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='newRelease',
            field=models.BooleanField(default=False),
        ),
    ]
