# Generated by Django 3.2 on 2021-04-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_apparel', '0006_product_newrelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inStock',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
