# Generated by Django 3.2 on 2021-04-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_apparel', '0007_alter_product_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gender',
            field=models.CharField(blank=True, default='male', max_length=200, null=True),
        ),
    ]
