# Generated by Django 3.2 on 2021-10-18 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan_apparel', '0008_product_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingCost',
            new_name='shippingPrice',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='taxCost',
            new_name='taxPrice',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totalCost',
            new_name='totalPrice',
        ),
    ]
