# Generated by Django 3.2 on 2021-10-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_apparel', '0010_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
